### PR TITLE
Initial code commit

### PR DESCRIPTION
**Pull request by mdholloway**

### CODE REVIEW

**Comment by berndsi** [comment]
@mdholloway Is the code the same as for the Chrome/FF extensions? 
If so, is there a good way to not duplicate the code?
Will there be a README with instructions on how to use it?

**Comment by mdholloway** [comment]
@berndsi The code is similar but differs anywhere we need to interact with the Safari APIs.  One significant difference is that here we end up passing the popover object around in order to manually resize it based on the content, since Safari doesn't do that for us.  There are other differences around message passing between the content page and the extension, and when opening new pages/tabs.  Unfortunately there's no handy polyfill script available that lets us get away with using the exact same code as with FF/Chrome.  

At least some of the code (such as that interacting with our APIs) could be moved to a shared library.  I guess that depends how much engineering time we want to put into this, considering the idea was that writing these browser extensions would be a quick, one-off project.  That said, I suppose we are blocked on Legal before we can release them in any case. 

I'll push a follow-up commit with a README.

**Comment by coreyfloyd** [comment]
@berndsi @mdholloway Just to chime in here…

I do think we should explore extracting a library after release if we are going to seriously maintain these and add features.  For now and on this initial commit I think we are good though. its different enough that it is a pain in the ass.

@berndsi is that ok with you to leave this code a separate for now?

Tangent:
I'd honestly thing is would be a cool project to make a JS library to interact with the full API and make it available to third parties. I think spending our time doing that would be an awesome way to contribute back to open source.

**Comment by berndsi** [comment]
Sure, keeping them separate for now is fine with me. Was just curious if there are any big differences. I have not run a diff on these yet.

**Review by tgr — APPROVED** [review]

**Comment by tgr** [comment]
A JS library for handling API corner cases like login or token fetch, or converting URLs into titles, would be nice, but probably would have to be written with different compatibility assumptions in mind (there are a lot of ES6 features used here that aren't supported by all browsers).

**Pull request merged**
